/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#define GCC_MAJOR 4
#define HOST_ARM 1
#define TCC_VERSION "0.9.25"
#define TCC_ARM_EABI 1
#define FORTIFY_SOURCE 0
#define TCC_TARGET_ARM 1
#define TCC_ARM_EABI 1
#define WITHOUT_LIBTCC 1
